//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Teacher
    {
        public byte TeacherId { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
        public Nullable<byte> TeacherBranch { get; set; }
        public string TeacherNumber { get; set; }
        public string TeacherPassword { get; set; }
    
        public virtual Tbl_Class Tbl_Class { get; set; }
    }
}
